### ISSUE TITLE
Error during rendering report

### ISSUE THREAD

**Issue by danieloquendo** [pofider/phantom-html-to-pdf#68]
I'm working on a web application using phantom-html-to-pdf, localmente works but in production the following error occurs

Error during rendering report: spawn /opt/venfi/node_modules/phantom-html-to-pdf/node_modules/phantomjs/lib/phantom\phantomjs.exe ENOENT

Centos
Node v6.10.3

Any idea what could be the issue here?
Thank you.

**Comment by bjrmatos** [comment]
it seems like you are working locally in a `Windows` machine, and that the way that you are passing your code to your production environment is to copy the folder of your `Windows` machine into your `Centos`, this is not the best way to install software between different OS, i mean you can copy all your templates, css, etc normally but dependencies (like `node_modules`) is another story because usually they will be executables that are specific to the target OS, this is current the problem that you have, you are using a windows executable `phantomjs.exe` inside a Linux machine, which is wrong, to solve your problem just delete the `node_modules` folder of your `Centos` and run `npm install` to install the dependencies again, this will download the correctly phantomjs executable for `Centos`.

Note: you will probably need to install some [additionally packages](https://github.com/pofider/phantom-html-to-pdf#installation-troubleshooting) when you are using phantomjs in Linux
